[build]
  command = "pip install -r requirements.txt && pip install -r functions/requirements.txt"
  publish = "."

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions."trade-analysis"]
  external_node_modules = ["supabase", "python-dotenv"]

[functions."health"] 
  external_node_modules = ["python-dotenv"] 